### ISSUE TITLE
AbstractDiscipline deploy failing

### ISSUE THREAD

**Issue by jbussemaker** [daniel-de-vries/OpenLEGO#10]
Tested with Anaconda Python 3.6.

When running the Sellar test problem, the AbstractDiscipline deploy function is failing because the XML files are opened in w-mode while the etree.tostring methods as used by the Sellar problem disciplines are returning byte arrays.

The reason for this is a well-known Python bug (or can we call it a feature?):
https://bugs.python.org/issue10942
https://docs.python.org/3/library/xml.etree.elementtree.html#xml.etree.ElementTree.tostring

Suggest to resolve it by writing a new XML-utils function that makes sure that the output of etree.tostring always is of string type.

**Comment by daniel-de-vries** [comment]
Does this issue also occur with Python 2.7?

**Comment by jbussemaker** [comment]
No it does not

**Comment by daniel-de-vries** [comment]
Since OpenLEGO depends on kadmos, which targets only Python 2.7, I think the best way to move forward is to change OpenLEGO's target to only support Python 2.7 as well. This would resolve this issue.

**Comment by daniel-de-vries** [comment]
Target Python 3.6 removed from setup.py. Closing this issue.
