### ISSUE TITLE
DictValues and DictKeys indexing

### ISSUE THREAD

**Issue by jbussemaker** [daniel-de-vries/OpenLEGO#11]
Calling .values() or .keys() on a dict returns a dictview object which does not support direct indexing: https://stackoverflow.com/a/18552025

This applies to:
- XMLComponent.write_input_file
- LEGOModel.coupling_var_cons

**Comment by daniel-de-vries** [comment]
Same as in issue #10: in the future only Python 2.7 should be targeted due to OpenLEGO's dependencies.

**Comment by daniel-de-vries** [comment]
Target Python 3.6 removed from setup.py. Closing this issue.
